table 'Key Measures'
	lineageTag: 4b3146f9-c853-4c97-b2b5-bc37e5f53696

	measure 'Expense Actual' = SUM(Data[Expense_Actual])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Expense
		lineageTag: a22c952e-21aa-448a-9456-3a610a3d87c8

	measure 'Income Actual' = SUM(Data[Income_Actual])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Income
		lineageTag: f19bca1f-db3e-4d6b-9593-a81499b5cf2a

	measure 'Income Budget' = SUM(Data[Income_Budget])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Income
		lineageTag: f66302b3-41da-4ecb-b460-0dad2a7905d7

	measure 'Expense Budget' = SUM(Data[Expense_Budget])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Expense
		lineageTag: 3a6e7dd7-964a-4180-b58c-34f5eb370bc3

	measure 'Expense Variance %' =
			
			DIVIDE(
			    [Expense Actual] - [Expense Budget],
			    [Expense Budget],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Expense
		lineageTag: e8fc1b7f-cbad-40ca-a791-dd0f3acd86e8

	measure 'Income Variance %' =
			
			DIVIDE(
			    [Income Actual] - [Income Budget],
			    [Income Budget],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Income
		lineageTag: 31592979-5796-4bd7-8807-965285e50691

	measure 'Expense Variance Conditional Formatting' =
			
			VAR _variance = [Expense Variance %]
			RETURN
			FORMAT(_variance,"#.##%") &" "& IF(_variance > 0, "🔺", "🔻")
		displayFolder: Expense
		lineageTag: 51d76582-8bef-4fe4-a971-aabd850fbada

	measure 'Income Variance Conditional Formatting' =
			
			VAR _variance = [Income Variance %]
			RETURN
			FORMAT(_variance,"#.##%") &" "& IF(_variance > 0, "🔺", "🔻")
		displayFolder: Income
		lineageTag: 8952c1fc-537e-4095-895e-7a5f1a7b450f

	measure '% of Expense Budget' =
			
			DIVIDE([Expense Actual],[Expense Budget],0)
		displayFolder: Expense
		lineageTag: 4afcf4f7-fc8e-465a-9cb9-dbfdd4a91b10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% of Income Budget' =
			
			DIVIDE([Income Actual],[Income Budget],0)
		displayFolder: Income
		lineageTag: 94ac6d0b-486d-4575-8021-03d9c914d10b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expense Donut Chart' = ```
			
			VAR ProgressValue = [% of Expense Budget]* 100 // Current progress (0-100).
			VAR DisplayValue = MIN(ProgressValue, 100) // Ensure that the donut chart does not exceed 100% visually
			VAR Radius = 42 // Radius of the donut chart
			VAR CircumferenceValue = 2 * PI() * Radius // Full circumference of the circle
			VAR ProgressLength = (DisplayValue / 100) * CircumferenceValue // Length of the progress stroke
			VAR CenterX = 60 // X-coordinate of the center
			VAR CenterY = 60 // Y-coordinate of the center
			VAR BackgroundStrokeWidth = 12 // Width of the background ring
			VAR ProgressStrokeWidth = 16 // Width of the progress ring
			
			// --- COLOR DEFINITIONS ---
			VAR RedColor = "#FF0000"     // Red color for overspending (>95%)
			VAR AmberColor = "#FFA500"   // Amber color for exactly 95%
			VAR GreenColor = "#13A806"   // Green color for under 95%
			
			// --- TARGET THRESHOLDS ---
			// Determines the final color based on ProgressValue (Expense % of Budget):
			// - Below 95% = Green
			// - Exactly 95% = Amber
			// - Above 95% = Red
			VAR FinalColor =
			SWITCH(
			    TRUE(),
			    ProgressValue < 95, GreenColor,       // Target: <95% = Green (on target)
			    ProgressValue = 95, AmberColor,       // Target: 95% = Amber (watch closely)
			    ProgressValue > 95, RedColor,         // Target: >95% = Red (overspent)
			    GreenColor                            // Default to Green if no conditions match
			)
			
			
			
			RETURN
			"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 120' width='260' height='260'>
			
			<style> @keyframes progress-fill { 0% { stroke-dashoffset: " & CircumferenceValue & "; stroke: " & RedColor & "; } 50% { stroke-dashoffset: " & (CircumferenceValue - (CircumferenceValue * 0.5)) & "; stroke: " & AmberColor & "; } 80% { stroke-dashoffset: " & (CircumferenceValue - (CircumferenceValue * 0.8)) & "; stroke: " & AmberColor & "; } 100% { stroke-dashoffset: " & (CircumferenceValue - ProgressLength) & "; stroke: " & FinalColor & "; } // Final color depends on ProgressValue } .progress-ring { animation: progress-fill 2s ease-out forwards; } </style> <circle cx='" & CenterX & "' cy='" & CenterY & "' r='" & Radius & "' fill='none' stroke='#E0E0E0' stroke-width='" & BackgroundStrokeWidth & "' /> <circle class='progress-ring' cx='" & CenterX & "' cy='" & CenterY & "' r='" & Radius & "' fill='none' stroke='" & FinalColor & "' stroke-width='" & ProgressStrokeWidth & "' stroke-dasharray='" & CircumferenceValue & "' stroke-dashoffset='" & (CircumferenceValue - ProgressLength) & "' /> <text x='50%' y='55%' text-anchor='middle' alignment-baseline='middle' font-size='18' font-family='Arial' fill='#444'>" & FORMAT(ProgressValue, "0.00") & "%</text> </svg>"
			
			```
		displayFolder: Expense
		lineageTag: d510e546-377e-4d8e-a85e-8cf0bd50e317
		dataCategory: ImageUrl

	measure 'Income Donut Chart' = ```
			
			VAR ProgressValue = [% of Income Budget]* 100 // Current progress (0-100).
			VAR DisplayValue = MIN(ProgressValue, 100) // Ensure that the donut chart does not exceed 100% visually
			VAR Radius = 42 // Radius of the donut chart
			VAR CircumferenceValue = 2 * PI() * Radius // Full circumference of the circle
			VAR ProgressLength = (DisplayValue / 100) * CircumferenceValue // Length of the progress stroke
			VAR CenterX = 60 // X-coordinate of the center
			VAR CenterY = 60 // Y-coordinate of the center
			VAR BackgroundStrokeWidth = 12 // Width of the background ring
			VAR ProgressStrokeWidth = 16 // Width of the progress ring
			
			// --- COLOR DEFINITIONS ---
			VAR RedColor = "#FF0000"     // Red color for underperforming (<95%)
			VAR AmberColor = "#FFA500"   // Amber color for exactly 95%
			VAR GreenColor = "#13A806"   // Green color for >95%
			
			// --- TARGET THRESHOLDS ---
			// Determines the final color based on ProgressValue (Income % of Budget):
			// - Below 95% = Red
			// - Exactly 95% = Amber
			// - Above 95% = Green
			VAR FinalColor =
			SWITCH(
			    TRUE(),
			    ProgressValue < 95, RedColor,       // Target: <95% = Red (underperforming)
			    ProgressValue = 95, AmberColor,     // Target: 95% = Amber (monitor closely)
			    ProgressValue > 95, GreenColor,     // Target: >95% = Green (on or above target)
			    GreenColor                          // Default to Green if no conditions match
			)
			
			RETURN
			"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 120' width='260' height='260'>
			
			<style> @keyframes progress-fill { 0% { stroke-dashoffset: " & CircumferenceValue & "; stroke: " & RedColor & "; } 50% { stroke-dashoffset: " & (CircumferenceValue - (CircumferenceValue * 0.5)) & "; stroke: " & AmberColor & "; } 80% { stroke-dashoffset: " & (CircumferenceValue - (CircumferenceValue * 0.8)) & "; stroke: " & AmberColor & "; } 100% { stroke-dashoffset: " & (CircumferenceValue - ProgressLength) & "; stroke: " & FinalColor & "; } // Final color depends on ProgressValue } .progress-ring { animation: progress-fill 2s ease-out forwards; } </style> <circle cx='" & CenterX & "' cy='" & CenterY & "' r='" & Radius & "' fill='none' stroke='#E0E0E0' stroke-width='" & BackgroundStrokeWidth & "' /> <circle class='progress-ring' cx='" & CenterX & "' cy='" & CenterY & "' r='" & Radius & "' fill='none' stroke='" & FinalColor & "' stroke-width='" & ProgressStrokeWidth & "' stroke-dasharray='" & CircumferenceValue & "' stroke-dashoffset='" & (CircumferenceValue - ProgressLength) & "' /> <text x='50%' y='55%' text-anchor='middle' alignment-baseline='middle' font-size='18' font-family='Arial' fill='#444'>" & FORMAT(ProgressValue, "0.00") & "%</text> </svg>"
			
			```
		displayFolder: Income
		lineageTag: cae56485-4903-4dac-8067-d0b7ed7c31e8
		dataCategory: ImageUrl

	measure 'Income Bar Chart' = ```
			
			VAR ProgressValue = [% of Income Budget]  * 100
			VAR BarHeight = 20
			VAR BarY = 20
			
			// --- COLOR DEFINITIONS ---
			VAR RedColor = "#FF0000"
			VAR AmberColor = "#FFA500"
			VAR GreenColor = "#13A806"
			
			VAR FinalColor =
			   SWITCH(
			    TRUE(),
			    ProgressValue < 95, RedColor,       // Target: <95% = Red (underperforming)
			    ProgressValue = 95, AmberColor,     // Target: 95% = Amber (monitor closely)
			    ProgressValue > 95, GreenColor,     // Target: >95% = Green (on or above target)
			    GreenColor                          // Default to Green if no conditions match
			)
			VAR ProgressPercent = DIVIDE(ProgressValue, 100, 0)
			
			RETURN
			"data:image/svg+xml;utf8,
			<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100' preserveAspectRatio='none' width='100%' height='50'>
			    <rect x='0' y='" & BarY & "' width='100' height='" & BarHeight & "' fill='#E0E0E0' rx='5' ry='5'/>
			    <rect x='0' y='" & BarY & "' width='" & (ProgressPercent * 100) & "' height='" & BarHeight & "' fill='" & FinalColor & "' rx='5' ry='5'/>
			    
			</svg>"
			
			```
		displayFolder: Income
		lineageTag: 506cceca-ce32-4849-bddb-61919695bef1
		dataCategory: ImageUrl

	measure 'Expense Bar Chart' = ```
			
			VAR ProgressValue = [% of Expense Budget] * 100
			VAR BarHeight = 20
			VAR BarY = 20
			
			// --- COLOR DEFINITIONS ---
			VAR RedColor = "#FF0000"
			VAR AmberColor = "#FFA500"
			VAR GreenColor = "#13A806"
			
			VAR FinalColor =
			SWITCH(
			    TRUE(),
			    ProgressValue < 95, GreenColor,       // Target: <95% = Green (on target)
			    ProgressValue = 95, AmberColor,       // Target: 95% = Amber (watch closely)
			    ProgressValue > 95, RedColor,         // Target: >95% = Red (overspent)
			    GreenColor                            // Default to Green if no conditions match
			)
			
			VAR ProgressPercent = DIVIDE(ProgressValue, 100, 0)
			
			RETURN
			"data:image/svg+xml;utf8,
			<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100' preserveAspectRatio='none' width='100%' height='50'>
			    <rect x='0' y='" & BarY & "' width='100' height='" & BarHeight & "' fill='#E0E0E0' rx='5' ry='5'/>
			    <rect x='0' y='" & BarY & "' width='" & (ProgressPercent * 100) & "' height='" & BarHeight & "' fill='" & FinalColor & "' rx='5' ry='5'/>
			    
			</svg>"
			
			```
		displayFolder: Expense
		lineageTag: 4f9c5a77-81e5-46af-8385-501acbb5de39
		dataCategory: ImageUrl

	measure 'Dynamic Header' =
			
			"Year: " & SELECTEDVALUE(DateTable[Year]) &
			" | Month: " & SELECTEDVALUE(DateTable[Month Name]) &
			" | Project ID: " & SELECTEDVALUE(Data[Project_ID])
		lineageTag: 770bc5af-9984-4440-8e8c-8faf590b7263

	partition 'Key Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

